[package]
name = "dns"
version = "0.1.0"
edition = "2024"

[dependencies]
rustls = "0.23.25"
tokio = { version = "1.44.1", features = ["full"] }
tokio-rustls = "0.26.2"
hyper = "1.6.0"
bytes = "1.10.1"
derive_builder = "0.20.2"
faster-hex = "0.10.0"